BANK_NIFTY_TRADING_SYMBOL = "NIFTY BANK"
BANKNIFTY_2024_PREFIX = "BANKNIFTY24"
BANK_NIFTY_LOT_SIZE = 15
NIFTY_BANK_INSTRUMENT_TOKEN = None  # This will be loaded from the NSE_instruments.json file

NIFTY_TRADING_SYMBOL = "NIFTY"
NIFTY_2024_PREFIX = "NIFTY24"
NIFTY_LOT_SIZE = 25
NIFTY_INSTRUMENT_TOKEN = None  # This will be loaded from the NSE_instruments.json file

